--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MintoD/AdvancedPluginManager
build-by-default: true
branches:
- main
- pm-4
projects:
  AdvancedPluginManager:
    path: ""
    libs:
    - src: dktapps-pm-pl/pmforms/pmforms
      version: ^2.0.0
    - src: CortexPE/Commando/Commando
      version: ^2.1.1
    - src: MintoD/libMCUnicodeChars/libMCUnicodeChars
      version: ^1.1.0
    lint:
      phpstan: false
...
