name: AdvancedPluginManager
author: thebigcrafter
description: A plugin manager for PocketMine-MP
version: 1.0.0-alpha
api: [3.0.0]
main: thebigcrafter\APM\APM

permissions:
  apm.cmd:
    description: Allows player to use the /apm command
    default: op