name: AdvancedPluginManager
author: thebigcrafter
description: A plugin manager for PocketMine-MP
version: 1.0.0-alpha5
api: 4.0.0
main: thebigcrafter\APM\APM
src-namespace-prefix: thebigcrafter\APM

permissions:
  apm.cmd:
    description: Allows player to use the /apm command
    default: op