name: PHPStan

on:
  push:
  pull_request:

jobs:
  build:
    name: PHPStan analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.0"

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php }}

      - name: Create vendor directory
        run: mkdir vendor
      
      - name: Download pmforms
        uses: wei/wget@v1
        with:
          args: -O vendor/pmforms.phar https://poggit.pmmp.io/r/149990/pmforms_dev-12.phar

      - name: Install PHPStan Composer dependencies
        run: composer install --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Run PHPStan
        run: composer run-script analyse-src
